apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  labels: 
    app.kubernetes.io/instance: test-chatbot-8
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name:  test-chatbot-8
    app.kubernetes.io/part-of: test-chatbot-8  
  name: test-chatbot-8
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance:  test-chatbot-8 
  template:
    metadata: 
      labels:
        app.kubernetes.io/instance:  test-chatbot-8
    spec:
      containers:
      - image:  quay.io/redhat-ai-dev/ai-template-bootstrap-app:latest
        name: app-inference
        envFrom:
        - configMapRef:
            name: test-chatbot-8-model-config
        env:
        - name: MODEL_ENDPOINT_API_KEY
          valueFrom:
            secretKeyRef:
              name: 
              key: 
        ports:
        - containerPort: 8501
        securityContext:
          runAsNonRoot: true
